//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressoUrbano.Presentation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExpressoUrbano.Presentation.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso negado!.
        /// </summary>
        public static string acesso_negado {
            get {
                return ResourceManager.GetString("acesso_negado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados alterado com sucesso!.
        /// </summary>
        public static string altera_sucesso {
            get {
                return ResourceManager.GetString("altera_sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao cadastrar!.
        /// </summary>
        public static string cadastro_erro {
            get {
                return ResourceManager.GetString("cadastro_erro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro realizado com sucesso!.
        /// </summary>
        public static string cadastro_sucesso {
            get {
                return ResourceManager.GetString("cadastro_sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao editar!.
        /// </summary>
        public static string edicao_erro {
            get {
                return ResourceManager.GetString("edicao_erro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edição realizada com sucesso!.
        /// </summary>
        public static string edicao_sucesso {
            get {
                return ResourceManager.GetString("edicao_sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao enviar email!.
        /// </summary>
        public static string email_erro {
            get {
                return ResourceManager.GetString("email_erro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email enviado com sucesso!.
        /// </summary>
        public static string email_sucesso {
            get {
                return ResourceManager.GetString("email_sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao excluir!.
        /// </summary>
        public static string exclusao_erro {
            get {
                return ResourceManager.GetString("exclusao_erro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão realizada com sucesso!.
        /// </summary>
        public static string exclusao_sucesso {
            get {
                return ResourceManager.GetString("exclusao_sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não há dados para exibir.
        /// </summary>
        public static string grid_vazia {
            get {
                return ResourceManager.GetString("grid_vazia", resourceCulture);
            }
        }
    }
}
